from SpencerLimitEquilibrium.CharacteristicsOfSlopeGeometryAttribute import CharacteristicsOfSlopeGeometryAttribute
from SpencerLimitEquilibrium.NumberOfSlices import NumberOfSlices
from SpencerLimitEquilibrium.CharacteristicsOfSlopeGeometry import CharacteristicsOfSlopeGeometry
from SpencerLimitEquilibrium.SlipSurface import SlipSurface
from SpencerLimitEquilibrium.PropertiesMaterials import PropertiesMaterials
from SpencerLimitEquilibrium.Forces import Forces
from SpencerLimitEquilibrium.WetSpecificWeight import WetSpecificWeight
from SpencerLimitEquilibrium.ImportantCoordinatesCircle import ImportantCoordinatesCircle
from SpencerLimitEquilibrium.WidthSlices import WidthSlices




def Formol():



    return 0